name: Build, Publish and Release
on:
  push:
    branches:
      - 'develop'
    tags:
      - '*'

jobs:
  build:
    runs-on: [self-hosted, arm64, 8gb]
    steps:
      - uses: actions/checkout@v3

      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MAC_AWS_AK }}
          aws-secret-access-key: ${{ secrets.MAC_AWS_SK }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ secrets.MAC_ECR_ACCOUNT_ID }}

      - name: Setup docker meta
        id: docker-meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/mac-background-check-dashboard
          tags: |
            type=semver,pattern={{version}}
            type=sha,prefix=,suffix=,format=short
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: |
            /tmp/.buildx-cache
            /tmp/.docker-image/${{ github.sha }}
          key: ${{ runner.os }}-buildx
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set outputs
        id: ref
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          tags: ${{ steps.docker-meta.outputs.tags }}
          build-args: |
            BUILD_NUMBER=${{ steps.ref.outputs.sha_short }}
            PUBLIC_URL=${{ secrets.PUBLIC_URL }}
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
